# Site settings
title: Rui Mourato's Blog
#email: 
description: > # ignore newlines until next variable
  Rui Mourato's Technical Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruimourato.com"

# Usernames
user_twitter: ruimourato
user_github: rmourato
user_linkedin: rmourato
user_disqus: ruimourato

# Pagination
paginate: 10
paginate_path: "blog/page:num"

# Analytics
#google_analytics: UA-63241218-1

# Build settings
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

# Automatic sitemap generation
gems:
  - jekyll-paginate
  - jekyll-sitemap


