# SITE CONFIGURATION
baseurl: ""
url: "http://ruimourato.com"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Rui Mourato's Blog
  avatar: avatar.jpg
  gravatar: # Email MD5 hash
  description: "Rui Mourato's Blog"

  # Header and footer text
  #header_text: >
  #   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  #
  #   <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  footer_text: >
   &copy; 2015 Rui Mourato. Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  #email_address: 
  #behance:
  #bitbucket:
  #dribbble:
  #facebook:
  #flickr:
  github: rmourato
  #google_plus:
  #instagram:
  linkedin: rmourato
  #pinterest:
  #reddit:
  #soundcloud:
  #stack_exchange:  # Full URL
  #steam:
  #tumblr:
  twitter: ruimourato
  #wordpress:
  #youtube:

  # Scripts
  google_analytics: UA-63241218-1
  disqus_shortname: ruimourato
  #katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

# Automatic sitemap generation
gems:
  - jekyll-sitemap
